project:
  type: website

website:
  favicon: "images/Crest.png"
  title: "HILLHEAD ULTIMATE"
  navbar:
    background: primary
    logo: "images/Crest.png"
    collapse: true
    pinned: true
    left:
      - text: "Offence"
        menu:
          - href: offence_principles.qmd
            text: Principles
      - text: "Defence"
        menu:
          - href: defence_principles.qmd
            text: Principles
format:
  html:
    theme:       
      - cosmo
      - styles.scss
    toc: true
    toc-depth: 3
    link-external-newwindow: true

editor: source

